# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Отслеживаемые ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Укажите нужную версию Python

      - name: Установить Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Укажите нужную версию Node.js

      - name: Установить зависимости Python
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Установить зависимости Node.js
        run: npm install

      - name: Сборка CSS
        run: npm run build:css

      - name: Сборка сайта
        run: mkdocs build

      - name: Минификация HTML
        run: npm run minify:html

      - name: Копирование собранных файлов в /docs
        run: |
          cp -r site/* docs/

      - name: Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs



