version: '3'
services:
  nginx:
    image: kirillkon1/custom-nginx:latest
    ports:
      - "8081:80"
    depends_on:
      - wsgi
  wsgi:
    image: kirillkon1/custom-wsgi:latest
    ports:
      - "8082:80"
